version: 2
jobs:
  build-deploy:
    docker:
      - image: circleci/python:stretch-node
    environment:
      CIRCLE_BUILD_DIR: $HOME/$CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - run:
          name: Install yarn packages
          command: yarn
      - run:
          name: Build project
          command: yarn run build
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync dist/ s3://github-time/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy
